# Generated by Django 5.0.6 on 2024-05-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=100)),
                ('spice', models.SmallIntegerField(default=0)),
                ('allergens', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('dine_in', models.BooleanField(default=True)),
                ('pickup_time', models.TimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro_app.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro_app.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro_app.menuitem')),
            ],
        ),
    ]
