# Generated by Django 5.0.6 on 2024-05-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='backend_bistro_app.customerorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro_app.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
