# Generated by Django 5.0.6 on 2024-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0005_alter_orderitem_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_item_2',
            field=models.ManyToManyField(through='backend_bistro_app.OrderItem', to='backend_bistro_app.menuitem'),
        ),
    ]
