# Generated by Django 5.0.6 on 2024-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0007_remove_orderitem_complete_remove_orderitem_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(default='1', max_length=12),
        ),
    ]
