# Generated by Django 5.0.6 on 2024-07-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0009_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 16, 15, 4, 14, 343871)),
        ),
    ]
