# Generated by Django 5.0.6 on 2024-07-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0012_rename_order_items_customerorder_order_item_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='order_item_2',
            new_name='order_items',
        ),
    ]
