# Generated by Django 5.0.6 on 2024-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0015_customerorder_dine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='dine_in',
            field=models.BooleanField(default=False),
        ),
    ]
