# Generated by Django 5.0.6 on 2024-07-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro_app', '0016_alter_customerorder_dine_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='order_items',
        ),
    ]
